services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=idp2025
      - MONGO_INITDB_ROOT_PASSWORD=idp2025
    command: ["mongod", "--quiet"]
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2g
          cpus: "1"

  io-backend:
    image: io-backend:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://idp2025:idp2025@mongo:27017/idp2025?authSource=admin
    depends_on:
      - mongo
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g
          cpus: "1"

volumes:
  mongo-data:

networks:
  app-network:
    external: true