name: CI/CD master

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Docker login
        run: docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build docker image
        run: docker build --pull -t ${{ secrets.REGISTRY_IMAGE }} .

      - name: Push docker image
        run: docker push ${{ secrets.REGISTRY_IMAGE }}

  deploy:
    name: Deploy
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
        run: curl -XPOST http://81.196.141.53:8000/portainer/api/webhooks/ed31282a-6924-4dc3-a07c-052c44b218b4
